### PR TITLE
Add kmuehlbauer as maintainer

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@keewis Do you happen to know, how we can prevent CI from running when merging this?

**Comment by kmuehlbauer** [comment]
@keewis Ready for merge.

**Comment by keewis** [comment]
> Do you happen to know, how we can prevent CI from running when merging this?

I don't. @ocepaf, do you have any advice here?

**Comment by kmuehlbauer** [comment]
> > Do you happen to know, how we can prevent CI from running when merging this?
> 
> I don't. @ocefpaf, do you have any advice here?

I've found it in the docs and prepared the commit message accordingly. Safe to merge AFAICT.

**Pull request merged**
