### PR TITLE
add packaging dep

### LINKED ISSUE #71: Import of xarray conda package fails for 0.21
It appears that the latest xarray conda package (0.21) does not pull in all the necessary dependencies.
One of our conda-forge builds fails when importing xarray:
```
    import xarray as xr
  File "/home/conda/feedstock_root/build_artifacts/bioimageio.core_1643501164132/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "/home/conda/feedstock_root/build_artifacts/bioimageio.core_1643501164132/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/home/conda/feedstock_root/build_artifacts/bioimageio.core_1643501164132/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/xarray/core/duck_array_ops.py", line 24, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/home/conda/feedstock_root/build_artifacts/bioimageio.core_1643501164132/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/xarray/core/dask_array_compat.py", line 4, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging
```
Pinning xarray to a version <0.21 removes this issue.
See https://github.com/conda-forge/bioimageio.core-feedstock/pull/15#issuecomment-1025107145 for more context.

### PR DESCRIPTION
**Pull request by jhamman**
closes #71 

xref: https://github.com/pydata/xarray/pull/6207

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jhamman** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@conda-grayskull show requirements

**Comment by conda-grayskull** [comment]
Working on your request...

**Comment by conda-grayskull** [comment]
================ **HOST** ================
Requirements for **host**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| python >=3.8 | python >=3.8 | :heavy_check_mark: |
| pip | pip | :heavy_check_mark: |
| setuptools_scm |  | :x: |
| | setuptools-scm | :heavy_plus_sign: |


================ **RUN** ================
Requirements for **run**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| python >=3.8 | python >=3.8 | :heavy_check_mark: |
| numpy >=1.18 | numpy >=1.18 | :heavy_check_mark: |
| pandas >=1.1 | pandas >=1.1 | :heavy_check_mark: |
| importlib_metadata |  | :x: |
| typing_extensions >=3.7 |  | :x: |
| packaging >=20.0 |  | :x: |

**Comment by ocefpaf** [comment]
@marcelotrevisani we have `setuptools_scm` but the bot suggested `setuptools-scm`. We need to standardized that.
Packaing was found but `importlib_metadata` and `typing_extensions >=3.7` probably have conditionals. I'll check later.

@jhamman sorry to hijack your PR but I wanted to take our new bot for a spin. This one is good to be merged!

**Pull request merged**
